"""add public_order_number to orders

Revision ID: 06ea4daf3af6
Revises: 793ed417282e
Create Date: 2025-10-18 20:11:02.778241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06ea4daf3af6'
down_revision = '793ed417282e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_order_number', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('public_order_number')

    # ### end Alembic commands ###
