"""add shipping_cost to order

Revision ID: 793ed417282e
Revises: 796fbe860a5e
Create Date: 2025-10-14 13:50:55.268037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '793ed417282e'
down_revision = '796fbe860a5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(
    sa.Column('shipping_cost', sa.Float(), nullable=False, server_default='0')
    )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('shipping_cost')

    # ### end Alembic commands ###
