"""add wholesale price

Revision ID: c0e695848e9e
Revises: 06ea4daf3af6
Create Date: 2026-02-18 12:34:59.826209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0e695848e9e'
down_revision = '06ea4daf3af6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_wholesale', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('price_wholesale')

    # ### end Alembic commands ###
